### ISSUE TITLE
Menu issue with another addon enabled

### ISSUE THREAD

**Issue by nancikennedy** [erglo/mission-report-button-plus#2]
On Retail, using MRBP v0.10.0 and [War Plan v3.22](https://www.curseforge.com/wow/addons/war-plan), the MRBP minimap button is not registering any of the custom options for the menu or showing summaries. I looked it up and didn't see any documentation that War Plan  "did" stuff to the MM button and there are no settings in game for WP.

My Settings:
![mrbpoptions](https://user-images.githubusercontent.com/8207666/217124661-e3ef26c0-81ca-4e73-af89-15830929a48f.png)

How it looks normally:
![mrbpokay](https://user-images.githubusercontent.com/8207666/217124701-6ff2ce4e-7cff-48f0-ace7-8dc9a8f783ec.png)

How it looks with War Plan enabled:
![mrbp](https://user-images.githubusercontent.com/8207666/217124766-79772e79-f5da-40e4-8af3-8910d31923ed.png)

**Comment by nancikennedy** [comment]
I also checked his Venture Plan/Master Plan addons for other expansion "garrison" content and neither of those is causing this issue.

**Comment by erglo** [comment]
Hi, thank you for reporting this!

> I also checked his Venture Plan/Master Plan addons for other expansion "garrison" content and neither of those is causing this issue.

You're right, neither `Venture Plan` nor `Master Plan` is causing this issue. If `War Plan` is used in combination with either one of the others, `MRBP` also works. I looked into the code of WP and it is using a button hook. Your 3rd screenshot shows the WP menu. It is definitely not the MRBP menu; your settings are ok.
I assume that, since WP loads after MRBP, it simply overrides the minimap button hook. Apparently the WoW UI can only handle the last applied hook for the same UI widget.

I will try to find a way to add a possibility to manually reload the minimap button hook. I'm not sure if this is possible though. As far as I know, hooking into the WoW UI widgets only works during the UI loading process, but I might be wrong.  

Currently you have only these three options:
- either use MRBP and WP together with VP and/or MP,
- or use MRBP without WP and/or VP/MP,
- or rename the first letter of the  `MissionReportButtonPlus` addon folder and the `MissionReportButtonPlus.toc` file in it to 'W', so it loads after WP. This also works. I just tried it.

**Comment by erglo** [comment]
Hi, I fixed it. Re-registering the minimap button hooks went smoother than expected.
`MRBP` checks now after loading if `War Plan` is installed, and automatically re-registers the needed hooks. I tested it and it works with all 3 addons mentioned above.
In case this happens again, I also added a slash command. Should something similar happen again, simply type `/mrbp hook` and it re-registers the needed hooks.

Have fun!
