### ISSUE TITLE
Add icon for in-game addon list

### ISSUE THREAD

**Issue by SpareSimian** [erglo/mission-report-button-plus#7]
Blizzard recently added the ability for addons to specify an icon to use in the in-game addon enable/disable list. Just add a line to your .toc file. It can specify either a built-in icon or one included in your addon. Here are some examples I grepped from my addons directory:
```
+Wowhead_Looter\+Wowhead_Looter.toc: ## IconTexture: Interface/Icons/ability_mount_rocketmount
AddonFactory\AddonFactory.toc: ## IconTexture: Interface\Icons\Achievement_guildperk_workingovertime
AdiBags_Bound\AdiBags_Bound.toc: ## IconTexture: Interface\Icons\inv_misc_bag_15
Altoholic\Altoholic.toc: ## IconTexture: Interface\Icons\inv_drink_13
HandyNotes_DragonGlyphs\HandyNotes_DragonGlyphs.toc: ## IconTexture: Interface/AddOns/HandyNotes_DragonGlyphs/icon.blp
MissingShadowlandsCompanions\MissingShadowlandsCompanions.toc: ## IconTexture: Interface\Icons\sanctum_features_missiontable
PotentialDarkmoonDecks\PotentialDarkmoonDecks.toc: ## IconTexture: Interface\Icons\Inv_inscription_darkmooncard_putrescence_a
Prat-3.0\Prat-3.0.toc: ## IconTexture: Interface\AddOns\Prat-3.0\textures\prat-logo-dark-small
SavedInstances\SavedInstances.toc: ## IconTexTure: Interface\AddOns\SavedInstances\Media\Icon.tga
```

**Comment by erglo** [comment]
Since v0.14.0 I already added the line 
`## IconAtlas: dragonflight-landingbutton-up` in the TOC file (line 25). This is the icon of the current Dragonflight expansion landing page button on the minimap. I thought this would be a good fit to represent the addon in-game.
Blizzard also uses the TOC file icon for the new Addon Compartment.

It is not the same icon I use as addon icon at the addon hosting websites, if it's that what you mean. Or isn't there any icon showing up at all in the addon list in your game? 
Please elaborate.

**Comment by SpareSimian** [comment]
Thanks, I somehow missed that! Sorry for the noise. It looks like IconAtlas was added in 10.1.0 and IconTexture might be the legacy line. That new Addon Compartment should be handy for my own addons!

https://wowpedia.fandom.com/wiki/TOC_format
https://wowpedia.fandom.com/wiki/Addon_compartment

**Comment by erglo** [comment]
> Sorry for the noise.

Don't worry about that. I welcome any kind of feedback.

Btw, you can even set both `IconTexture` and `IconAtlas` at the same time. In this case `IconTexture` will be prioritized.
